apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepositories.yaml
  - kube-prometheus-stack.yaml
  - loki.yaml
  - promtail.yaml
  - dashboards/gateway-kong.yaml
  - dashboards/cluster-capacity.yaml
  - dashboards/logs-loki.yaml
  - dashboards/batch-settlement.yaml
