apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../_base]
namePrefix: response-template-
labels:
  - pairs:
      app.kubernetes.io/name: response-template
      gateflow.io/support-role: response-template
    includeSelectors: true
    includeTemplates: true
patches:
  - target:
      kind: Deployment
      name: worker
    patch: |
      - op: add
        path: /spec/template/metadata/annotations
        value:
          gateflow.io/release: baseline
