apiVersion: v1
kind: ServiceAccount
metadata:
  name: chat-svc
  namespace: team-chat
  annotations:
    # From `pulumi stack output chatSvcClientId` (id-chat-svc-dev identity).
    azure.workload.identity/client-id: "254534ba-1115-4cf9-81bd-6c36d95ac3aa"
