apiVersion: v1
kind: Service
metadata:
  name: chat-svc
  namespace: team-chat
spec:
  selector:
    app.kubernetes.io/name: chat-svc
  ports:
    - name: http
      port: 8000
      targetPort: http
